stages:
  - lint
  - test
  - build

variables:
  NODE_ENV: 'development'
  CACHE_PATHS: "client/node_modules server/node_modules"

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

before_script:
  - echo "Node version:"
  - node --version
  - echo "NPM version:"
  - npm --version

lint_client:
  stage: lint
  script:
    - cd client
    - npm ci
    - npm run lint

lint_server:
  stage: lint
  script:
    - cd server
    - npm ci
    - npm run lint

test_client:
  stage: test
  script:
    - cd client
    - npm ci
    - npm run test

test_server:
  stage: test
  script:
    - cd server
    - npm ci
    - npm run test

build_client:
  stage: build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/build

build_server:
  stage: build
  script:
    - cd server
    - npm ci
    - npm run build
  artifacts:
    paths:
      - server/dist
